version: "3.9"

services:
  # Adminer - Interface web pour MySQL
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: dracula
    depends_on:
      - database

  # MailHog - Capture et affichage des emails en développement
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  # PHP + FrankenPHP
  php:
    build:
      context: .
      target: frankenphp_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_ENV: dev
      APP_SECRET: ChangeMe
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy

  # MySQL
  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony-app
      MYSQL_USER: heleneadmin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      start_period: 30s

volumes:
  database_data:
